#!/usr/bin/env bash
# Symlink every bundled skill (m-*) into ~/.config/devin/skills so Devin CLI loads them.
# NEVER clobbers an existing REAL dir — preserves a user's own hand-authored skills
# (e.g. your original m-ask); only that user's missing skills get the vendored copy.
set -euo pipefail
PROJECT_DIR=""
TOOL_NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT_DIR="$2"; shift 2 ;;
    --tool)    TOOL_NAME="$2";    shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# Validate: --tool requires --project
if [ -n "$TOOL_NAME" ] && [ -z "$PROJECT_DIR" ]; then
  echo "Error: --tool requires --project <path>."
  echo "Example: bash install.sh --tool claude --project /path/to/your-project"
  exit 1
fi
SRC="$(cd "$(dirname "$0")" && pwd)"

# Global Devin install — only when no --project or --tool flag given
if [ -z "$PROJECT_DIR" ] && [ -z "$TOOL_NAME" ]; then
  DEST="$HOME/.config/devin/skills"
  mkdir -p "$DEST"
  for d in "$SRC"/m-*; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    if [ -e "$DEST/$name" ] && [ ! -L "$DEST/$name" ]; then
      echo "skip $name (your own real skill — left untouched)"; continue
    fi
    ln -sfn "$d" "$DEST/$name"
    echo "linked $name"
  done
  echo "Done. Restart Devin CLI or re-scan skills if needed."
fi

# --project: copy quality companion skills into a target project's .devin/skills/
# (only when --tool is not also given — --tool handles its own project install)
if [ -n "$PROJECT_DIR" ] && [ -z "$TOOL_NAME" ]; then
  QUALITY_SKILLS="m-security-and-hardening m-performance-optimization \
m-debugging-and-error-recovery m-api-and-interface-design m-frontend-ui-engineering"
  PROJ_DEST="$PROJECT_DIR/.devin/skills"
  mkdir -p "$PROJ_DEST"
  echo "Installing quality companion skills into $PROJ_DEST"
  for skill in $QUALITY_SKILLS; do
    src="$SRC/$skill"
    target="$PROJ_DEST/$skill"
    if [ ! -d "$src" ]; then
      echo "  WARN $skill not found in toolkit — run vendor.sh first"; continue
    fi
    if [ -e "$target" ]; then
      echo "  skip $skill (already exists in project — left untouched)"; continue
    fi
    cp -R "$src" "$target"
    echo "  installed $skill -> $target"
  done
  echo "Done. Restart Devin CLI in the project to load them."
fi

# --tool: write a non-Devin adapter + .sdd/pipeline.md into a target project
if [ -n "$TOOL_NAME" ]; then
  # Map tool name to target file path
  case "$TOOL_NAME" in
    claude)   ADAPTER_REL=".claude/CLAUDE.md" ;;
    cursor)   ADAPTER_REL=".cursorrules" ;;
    windsurf) ADAPTER_REL=".windsurfrules" ;;
    agents)   ADAPTER_REL="AGENTS.md" ;;
    *)
      echo "Error: unknown tool '$TOOL_NAME'. Supported: claude, cursor, windsurf, agents"
      exit 1
      ;;
  esac

  ADAPTER_PATH="$PROJECT_DIR/$ADAPTER_REL"
  ADAPTER_DIR="$(dirname "$ADAPTER_PATH")"

  echo "Installing SDD adapter for '$TOOL_NAME' into $PROJECT_DIR"

  # Create target dir if needed (e.g. .claude/)
  mkdir -p "$ADAPTER_DIR"

  # Never clobber an existing adapter file
  if [ -e "$ADAPTER_PATH" ]; then
    echo "  skip $ADAPTER_REL (already exists — delete it to regenerate)"
  else
    # Assemble adapter: header + shared rules + each phase in pipeline order
    {
      echo "# SDD Pipeline — $TOOL_NAME"
      echo ""
      echo "> Read this before running any SDD phase. This file was generated by"
      echo "> \`bash install.sh --tool $TOOL_NAME --project <path>\` from the SDD toolkit."
      echo ""
      echo "---"
      echo ""
      cat "$SRC/m-sdd/phase-instructions.md"
      echo ""
      for phase in constitution specify clarify plan tasks analyze implement; do
        pi="$SRC/m-sdd-$phase/phase-instructions.md"
        if [ -f "$pi" ]; then
          echo ""
          echo "---"
          echo ""
          cat "$pi"
        else
          echo ""
          echo "---"
          echo ""
          echo "# SDD — $phase phase"
          echo ""
          echo "> phase-instructions.md not found for this phase. Run vendor.sh to update."
        fi
      done
    } > "$ADAPTER_PATH"
    echo "  installed $ADAPTER_REL"
  fi

  # Write .sdd/pipeline.md if absent
  PIPELINE_DIR="$PROJECT_DIR/.sdd"
  PIPELINE_FILE="$PIPELINE_DIR/pipeline.md"
  mkdir -p "$PIPELINE_DIR"
  if [ -e "$PIPELINE_FILE" ]; then
    echo "  skip .sdd/pipeline.md (already exists)"
  else
    cat > "$PIPELINE_FILE" <<'PIPELINE_EOF'
# SDD Pipeline State

<!-- Managed by the SDD toolkit. Update phase rows as you work through the pipeline. -->
<!-- Status values: pending | in_progress | done | approved | skipped -->

## Feature: <!-- replace with your feature name -->  <!-- active -->

| Phase        | Status  |
|--------------|---------|
| constitution | pending |
| specify      | pending |
| clarify      | pending |
| plan         | pending |
| tasks        | pending |
| analyze      | pending |
| implement    | pending |
| issues       | pending |
PIPELINE_EOF
    echo "  installed .sdd/pipeline.md"
  fi

  echo "Done. Restart your AI tool in the project to load the adapter."
fi
