#!/usr/bin/env bash
# repo-map.sh — generate .sdd/repo-map.md: files + key symbols across the repo's
# languages. universal-ctags when present; zero-dependency grep fallback otherwise.
# Runs under bash and zsh. Usage: repo-map.sh <root> [--out <path>]
set -u

: "${RM_MAX_SYMS:=12}"    # max symbol lines per file
: "${RM_MAX_FILES:=400}"  # max files listed before truncation note

# Source files for the languages we map, pruning vendored/build/VCS dirs.
_rm_find_sources() { # <root> -> newline-separated file paths
  local root="$1"
  find "$root" \
    \( -type d \( -name node_modules -o -name .git -o -name build -o -name dist \
       -o -name Pods -o -name vendor -o -name .dart_tool -o -name .next \
       -o -name coverage -o -name .sdd \) \) -prune -o \
    -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' \
       -o -name '*.py' -o -name '*.kt' -o -name '*.java' -o -name '*.swift' \) -print \
    2>/dev/null
}

# Map a file list (stdin) to the distinct language labels present.
_rm_detect_langs() {
  sed -n -E \
    -e 's/.*\.(tsx?|jsx?)$/TypeScript-JavaScript/p' \
    -e 's/.*\.py$/Python/p' \
    -e 's/.*\.kt$/Kotlin/p' \
    -e 's/.*\.java$/Java/p' \
    -e 's/.*\.swift$/Swift/p' \
  | LC_ALL=C sort -u
}

# True only for universal-ctags. macOS ships BSD ctags at /usr/bin/ctags, whose
# --version prints nothing useful, so this correctly returns 1 there -> grep path.
_rm_has_universal_ctags() {
  command -v ctags >/dev/null 2>&1 || return 1
  ctags --version 2>/dev/null | grep -qi 'universal ctags'
}

# Extract definition/route lines from one file by extension. Output: "    Lnnn  <code>".
_rm_extract_grep() { # <file>
  local f="$1" pat
  case "$f" in
    *.ts|*.tsx|*.js|*.jsx)
      pat='^export (default )?(async )?(function|class|abstract class|const|interface|enum|type)[ <(]|^(async )?function [A-Za-z_]|router\.(get|post|put|delete|patch|use)\(' ;;
    *.py)
      pat='^[[:space:]]*(async def|def|class) [A-Za-z_]' ;;
    *.kt)
      pat='^[[:space:]]*(public |private |internal |protected |open |abstract |sealed |final |data |suspend )*(class|object|interface|enum class|fun) [A-Za-z_]' ;;
    *.java)
      pat='^[[:space:]]*(public|protected|private)[[:space:]].*(class|interface|enum|record)[[:space:]]|^[[:space:]]*(public|protected|private)[[:space:]].*[A-Za-z0-9_>]\([^)]*\)[[:space:]]*\{?[[:space:]]*$' ;;
    *.swift)
      pat='^[[:space:]]*(public |private |internal |fileprivate |open |final |static |@objc |override )*(class|struct|enum|protocol|extension|func) [A-Za-z_]' ;;
    *) return 0 ;;
  esac
  grep -nE "$pat" "$f" 2>/dev/null | cut -c1-120 | head -"$RM_MAX_SYMS" \
    | sed -E 's/^([0-9]+):[[:space:]]*/    L\1  /'
}

# Extract tags via universal-ctags as JSON, parse with jq into
# "<path>\t<line>\t<name>\t<kind>" rows. Auto-detects languages; prunes junk dirs.
_rm_extract_ctags() { # <root>
  local root="$1"
  ctags -R --output-format=json --fields='+n' \
    --exclude=node_modules --exclude=.git --exclude=build --exclude=dist \
    --exclude=Pods --exclude=vendor --exclude=.dart_tool --exclude=.next \
    --exclude=coverage --exclude=.sdd \
    -f - "$root" 2>/dev/null \
  | jq -r 'select(._type=="tag")
           | "\(.path)\t\(.line // 0)\tL\(.line // 0)  \(.name) [\(.kind // "?")]"'
}

# Print relative path (root prefix stripped, leading slash removed).
_rm_relpath() { printf '%s' "${1#"$2"}" | sed -E 's#^/##'; }

# Emit the full map to stdout for the resolved root.
_rm_emit() { # <root>
  local root="$1" mode files langs count=0 f rel out_syms
  if _rm_has_universal_ctags; then mode="universal-ctags"; else mode="grep"; fi
  files="$(_rm_find_sources "$root" | LC_ALL=C sort)"
  langs="$(printf '%s\n' "$files" | _rm_detect_langs | paste -sd ', ' - 2>/dev/null)"

  printf '# Repo Map — %s\n\n' "$(basename "$root")"
  printf '> Generated by m-sdd-knowledge (%s) on %s. Do NOT edit — regenerate by re-running the skill.\n' \
    "$mode" "$(date +%Y-%m-%d 2>/dev/null || echo unknown)"
  printf '> Languages: %s\n\n' "${langs:-none}"

  [ -n "$files" ] || { printf '_(no source files found)_\n'; return 0; }

  if [ "$mode" = "universal-ctags" ]; then
    # Group ctags rows by file; cap symbols per file.
    _rm_extract_ctags "$root" | LC_ALL=C sort -t "$(printf '\t')" -k1,1 -k2,2n \
    | awk -F '\t' -v root="$root" -v maxs="$RM_MAX_SYMS" '
        function rel(p){ sub("^" root, "", p); sub("^/", "", p); return p }
        { if ($1 != cur) { cur=$1; n=0; printf "\n▸ %s\n", rel(cur) }
          if (n++ < maxs) print $3 }'
  else
    # grep path: one section per file, in sorted order.
    printf '%s\n' "$files" | while IFS= read -r f; do
      [ -n "$f" ] || continue
      count=$((count+1))
      if [ "$count" -gt "$RM_MAX_FILES" ]; then
        printf '\n_(+ more files omitted — raise RM_MAX_FILES or use a code MCP)_\n'
        break
      fi
      out_syms="$(_rm_extract_grep "$f")"
      [ -n "$out_syms" ] || continue
      rel="$(_rm_relpath "$f" "$root")"
      printf '\n▸ %s\n%s\n' "$rel" "$out_syms"
    done
  fi
}

_rm_main() { # <root> [--out <path>]
  local root="." out=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --out) out="${2:-}"; shift 2 ;;
      *)     root="$1"; shift ;;
    esac
  done
  [ -d "$root" ] || { printf 'repo-map: not a directory: %s\n' "$root" >&2; return 1; }
  root="$(cd "$root" && pwd)"
  [ -n "$out" ] || { mkdir -p "$root/.sdd"; out="$root/.sdd/repo-map.md"; }
  _rm_emit "$root" > "$out"
  printf 'repo-map: wrote %s\n' "$out"
}

# Run main only when executed, not when sourced by the test suite.
[ -n "${REPO_MAP_SOURCED:-}" ] || _rm_main "$@"
